# Generated by Django 3.2.9 on 2021-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=20, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目名称', max_length=10, verbose_name='项目名称')),
                ('is_execute', models.BooleanField(default=True, help_text='项目是否启动（默认为启动）', verbose_name='项目是否启动（默认为启动）')),
                ('desc', models.TextField(blank=True, default='', help_text='项目描述', null=True, verbose_name='项目描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_projects',
            },
        ),
    ]
