# Generated by Django 3.2.9 on 2021-12-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211217_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='ids',
        ),
        migrations.AddField(
            model_name='projects',
            name='id',
            field=models.IntegerField(default=1, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
