# Generated by Django 3.1.6 on 2022-01-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211221_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['id'], 'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='leader',
            field=models.CharField(help_text='项目负责人', max_length=10, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
