# Generated by Django 3.1.6 on 2022-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220112_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.IntegerField(help_text='项目主键', primary_key=True, serialize=False, verbose_name='项目主键'),
        ),
    ]
