# Generated by Django 3.1.6 on 2022-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220112_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.IntegerField(help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
