# Generated by Django 3.1.6 on 2022-01-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20220112_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
