"""
Django settings for dev09 project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import sys
import os
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 因为把所有的子应用都移到了apps目录下，所有需要作如下操作
# sys.path是个列表，是Django依次寻找子应用的路径
# 先将BASE_DIR和apps拼接，再将其插入到sys.path的第一个位置，所以Django才能搜寻到子应用
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wssq5_!t!(mel9kfmsa4q1n6n0&r%%l_0sd+2r=1o3)=xd6m3f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 指定哪些地址可以访问当前项目
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 处理跨域请求步骤1、添加处理前端跨域的子应用
    'corsheaders',
    'rest_framework',
    'drf_yasg',
    'projects',
    'interfaces',
    'user',
    'testcases',
    'configures',
    'reports',
    'testsuites',
    'envs',
    'debugtalks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 处理跨域请求步骤2、添加处理跨域的中间件，必须在CommonMiddleware之前
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 处理跨域请求步骤3、允许所有域名访问后端接口，默认为False
CORS_ORIGIN_ALLOW_ALL = True
# 或者设置白名单
# CORS_ORIGIN_WHITELIST = [
#     'http://192.168.3.9:8080'
# ]
# 是否允许携带cookie
# CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'dev09.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dev09.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF中的解析器（类）
# 1、可以根据请求头中的Content-Type来自动解析参数，使用统一的data属性来获取即可
# 2、默认JSONParser、FormParser、MultiPartParser三个解析器类
# 3、可以在全局配置文件（settings.py）中修改DRF全局参数，REST_FRAMEWORK是固定写法
REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    # DRF中的渲染器
    # 1、可以根据请求头中的Accept参数来自动渲染前端需要的数据格式
    # 2、默认的渲染器为JSONRenderer、BrowsableAPIRenderer
    # 3、如果前端请求头未指定Accept参数或者指定为application/json，那么会自动返回json格式的数据
    # 4、如果前端请求头指定Accept参数为text/html，那么会返回html页面
    # 5、可以在DEFAULT_RENDERER_CLASSES中指定需要使用的渲染器
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # 在全局DEFAULT_FILTER_BACKENDS指定过滤用的引擎类（搜索和排序）
    # SEARCH_PARAM可以自定义搜索参数名称（默认为search）
    # ORDERING_PARAM可以自定义搜索参数名称（默认为ordering）
    'DEFAULT_FILTER_BACKENDS': ['rest_framework.filters.SearchFilter',
                                'rest_framework.filters.OrderingFilter'],
    # 'SEARCH_PARAM': 'se',
    # 'ORDERING_PARAM': 'or',
    # 指定分页引擎
    # PAGE_SIZE指定每页的条数
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # 测试平台接口文档的全局配置
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

    # 指定使用的认证类
    # a、在全局指定默认的认证类
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # a、使用jwt token认证
        # 1、在全局路由表中添加obtain_jwt_token路由
        # 2、前端传入用户名和密码
        # 3、后端返回token值
        # 4、前端在请求头中传递token，键为Authorization，值为JWT token值
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        # b、Session会话认证
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    ],
    # 指定使用的权限类
    # a、在全局指定默认的权限类（当认证通过之后，可以获取何种权限）
    # 'DEFAULT_PERMISSION_CLASSES': [
        # AllowAny不管是否成功认证，都能获取所有权限
        # IsAuthenticated只要登录，就具备所有权限
        # IsAdminUser管理员具有所有权限
        # IsAuthenticatedOrReadOnly，如果登录了就具备所有权限，不登录则为只读权限
        # 'rest_framework.permissions.AllowAny',
    # ],
}

# 指定User模型类
# AUTH_USER_MODEL = 'user.UserModel'

# token认证配置
JWT_AUTH = {
    # 修改认证请求头的前缀
    # 'JWT_AUTH_HEADER_PREFIX': 'bearer',
    # 修改token过期时间
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
    # 修改处理payload的函数
    'JWT_RESPONSE_PAYLOAD_HANDLER':
        'utils.response_payload_handler.jwt_response_payload_handler',
}

LOGGING = {
    # 指定日志版本
    'version': 1,
    # 是否禁用其他日志
    'disable_existing_loggers': False,
    # 定义日志输出格式
    'formatters': {
        # 复杂格式
        'verbose': {
            'format': '%(asctime)s - [%(levelname)s] - %(name)s - [msg]%(message)s - [%(filename)s:%(lineno)d ]'
        },
        # 简单格式
        'simple': {
            'format': '%(asctime)s - [%(levelname)s] - [msg]%(message)s'
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    # 指定日志输出渠道（日志输出的地方）
    'handlers': {
        # 指定在console控制台输出的日志配置信息
        'console': {
            # 指定日志记录等级
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 指定在文件输出的日志配置信息
        'file': {
            # 指定日志记录等级
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            # 日志保存位置
            'filename': os.path.join(BASE_DIR, "logs/mytest.log"),
            'maxBytes': 100 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
            # 写入的编码格式（以防中文乱码）
            'encoding': 'utf-8'
        },
    },
    # 定义日志器
    'loggers': {
        # 指定日志器的名称
        'mytest': {  # 定义了一个名为mytest的日志器
            'handlers': ['console', 'file'],
            'propagate': True,
            'level': 'DEBUG',  # 日志器接受的最低日志级别
        }
    }
}